version: 2.0
env:
    secrets-manager:
        TOKEN: thirdsecret:tokenforsonar
phases:
  install:
    runtime-versions:
      java: latest
  build:
    commands:
<<<<<<< HEAD
      - mvn verify sonar:sonar -Dsonar.projectKey=batumejavaprojectaws-3 -Dsonar.organization=batumejavaprojectaws-3 -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$TOKEN 
=======
      - mvn verify sonar:sonar -Dsonar.projectKey=batumejavaprojectaws-3 -Dsonar.organization=batumejavaprojectaws-3 -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$TOKEN
>>>>>>> 2cca91f7416fb7f89b7d4af0a01d397a9e9a7570
      - sleep 5
      - |-
        quality_status=$(curl -s -u $TOKEN: https://sonarcloud.io/api/qualitygates/project_status?projectKey=batumejavaprojectaws-3 | jq -r '.projectStatus.status')
        echo "SonarCloud analysistatus is $quality_status";
        if [ $quality_status = "ERROR" ] ; then exit 1;fi
